<?php

// Prevent direct file access
if( ! defined( 'SCCSS_FILE' ) ) {
	die();
}

/*
*
* @since  1.0
* @param  array $links Array of links generated by WP in Plugin Admin page.
* @return array        Array of links to be output on Plugin Admin page.
*/
function dropsoft_link( $links ) {
	return array_merge(
		array(
			'settings' => '<a href="' . admin_url( 'themes.php?page=dropsoft.php' ) . '">' . __( 'Api code invoeren', 'dropsoft' ) . '</a>'
		),
		$links
	);
}
add_filter( 'plugin_action_links_' . plugin_basename( SCCSS_FILE ), 'dropsoft_link' );



/**
* Delete Options on Uninstall
*
* @since 1.1
*/
function sccss_uninstall() {
	delete_option( 'dropsoft' );
}
register_uninstall_hook( SCCSS_FILE, 'sccss_uninstall' );



/**
 * Register "dropsoft" submenu in "Appearance" Admin Menu
 *
 * @since 1.0
 */
function sccss_register_submenu_page() {
	add_theme_page( __( 'Dropsoft Importer', 'dropsoft' ), __( 'Dropsoft import', 'dropsoft' ), 'edit_theme_options', basename( SCCSS_FILE ), 'sccss_render_submenu_page' );
}
add_action( 'admin_menu', 'sccss_register_submenu_page' );


/**
 * Register settings
 *
 * @since 1.0
 */
function sccss_register_settings() {
	register_setting( 'dropsoft_group', 'dropsoft' );
}
add_action( 'admin_init', 'sccss_register_settings' );


/**
 * Render Admin Menu page
 *
 * @since 1.0
 */
function sccss_render_submenu_page() {

	$options = get_option( 'dropsoft' );
	$content = isset( $options['sccss-content'] ) && ! empty( $options['sccss-content'] ) ? $options['sccss-content'] : __( '/* Voer uw persoonlijke api code hier in */', 'dropsoft' );

	if ( isset( $_GET['settings-updated'] ) ) : ?>
		<div id="message" class="updated"><p><?php _e( 'Dropsoft is gewijzigd.', 'dropsoft' ); ?></p></div>
	<?php endif; ?>
	<div class="wrap">
		<h2 style="margin-bottom: 1em;"><?php _e( 'Dropsoft product import', 'dropsoft' ); ?></h2>
		<form name="sccss-form" action="options.php" method="post" enctype="multipart/form-data">
			<?php settings_fields( 'dropsoft_group' ); ?>
			<div id="template">
				<?php do_action( 'sccss-form-top' ); ?>
				<div>
					<input type="text" style="width: 400px" id="api" name="dropsoft[sccss-content]" value="<?php echo esc_html( $content ); ?>">
				</div>
				<?php do_action( 'sccss-textarea-bottom' ); ?>
				<div>
					<?php submit_button( __( 'Verzenden', 'dropsoft' ), 'primary', 'submit', true ); ?>
				</div>
				<?php do_action( 'sccss-form-bottom' ); ?>
			</div>
		</form>

		<script type="text/javascript">
			jQuery(document).ready(function(){
				var tourl = window.location.host;
				var data = '';
				jQuery('#submit').click(function(){
					var api = jQuery("#api").val();
					jQuery.ajax({
					    url: "http://"+tourl+"/import.php?api="+api+"",
					    success: function(result){}
					});//end ajax
					console.log(api);
				});
			});
		</script>		

	</div>
<?php
}


